# Generated by Django 5.2.1 on 2025-10-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant_owner', 'Restaurant Owner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
