# Generated by Django 5.2.1 on 2025-08-17 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_created_at_customerorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customerorderitem'),
        ),
    ]
