# Generated by Django 5.2.1 on 2025-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customerorder_customerorderitem_delete_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='user',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
